name: Java CI with Maven (Multiple JVM Flags)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jvm_flag:
          - "-XX:+UseG1GC"
          - "-XX:ConcGCThreads=2"
          - "-XX:+PrintCompilation"
          - "-XX:+UnlockDiagnosticVMOptions"
          - "-XX:MaxInlineSize=128"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Test with Maven
        run: ./mvnw clean install -Dmaven.test.skip=false
        env:
          MAVEN_OPTS: "${{ matrix.jvm_flag }}"

      - name: Run tests with JVM flag
        run: ./mvnw test -Dmaven.test.failure.ignore=true
        env:
          MAVEN_OPTS: "${{ matrix.jvm_flag }}"
        continue-on-error: true

      - name: Generate JaCoCo Coverage Report
        run: ./mvnw jacoco:report

      - name: Display JaCoCo Coverage
        id: coverage
        run: |
          coverage=$(grep -oP '(?<=<counter type="LINE" missed=")[0-9]+(?=" covered=")[0-9]+' target/site/jacoco/jacoco.xml | awk '{sum+=$1} END {print sum}') 
          echo "Coverage with flag ${{ matrix.jvm_flag }}: $coverage"
          echo "COVERAGE=${coverage}" >> $GITHUB_ENV

      - name: Coverage Threshold Check
        run: |
          if [[ "$COVERAGE" -lt 24.46 ]]; then
            echo "Coverage did not meet threshold with flag ${{ matrix.jvm_flag }}"
            exit 1
          else
            echo "Coverage passed for flag ${{ matrix.jvm_flag }}"
          fi
